# =========================
# MQTT normal (backend)
# =========================
listener 1883
protocol mqtt

# =========================
# MQTT por WebSocket (frontend)
# =========================
listener 9001
protocol websockets

# =========================
# DEV ONLY
# =========================
allow_anonymous true
